schema: './src/lib/graphql/schema.graphql'
documents:
  - './src/**/*.{ts,tsx,js,jsx}'
  - './src/lib/graphql/**/*.graphql'
extensions:
  codegen:
    generates:
      './src/lib/types/generated/graphql.ts':
        plugins:
          - typescript
          - typescript-operations
          - typescript-graphql-request
    config:
      scalars:
        DateTime: string
        Any: any
