#!/bin/bash

TYPES_FILE="src/lib/types/index.ts"

NAMES=(
  "User"
  "UserFields"
  "UserSearchProps"
  "Team"
  "TeamFields"
  "TeamStats"
  "TeamWithStats"
  "TeamStat"
  "TeamCounts"
  "TeamFilters"
  "Game"
  "GameFields"
  "GameStats"
  "GameWithStats"
  "GameStat"
  "GameFilters"
  "GameLog"
  "GameLogInput"
  "GameLogStats"
  "GameLogFilters"
  "Friendship"
  "FriendRequest"
  "Notification"
  "NotificationType"
  "NotificationContextType"
  "ToasterToast"
  "Toast"
  "ToastAction"
  "ToastProps"
  "ToastActionElement"
  "ValidatableValue"
  "WithId"
  "WithTimestamps"
  "WithSoftDelete"
  "DateRange"
  "SortOption"
  "GroupRole"
  "ActivityType"
  "TeamAction"
  "TeamSort"
  "PlayerSort"
  "FriendshipStatusValue"
  "ChartType"
  "ReactionTarget"
  "RedisClientType"
  "Conference"
  "Division"
  "NBAPosition"
  "LeagueType"
  "FriendRequestButtonProps"
)

for NAME in "${NAMES[@]}"; do
  sed -i '' "/^export type $NAME /,/^}/d" "$TYPES_FILE"
  sed -i '' "/^export interface $NAME /,/^}/d" "$TYPES_FILE"
  sed -i '' "/^export enum $NAME /,/^}/d" "$TYPES_FILE"
  sed -i '' "/^export const $NAME /,/^};/d" "$TYPES_FILE"
done

sed -i '' '/^$/N;/^\n$/D' "$TYPES_FILE"

echo "Cleanup complete. Please review src/lib/types/index.types.ts for any remaining duplicates or manual tweaks."
