type Game {
  id: ID!
  date: GameDate!
  status: GameStatus!
  arena: Arena
  league: String
  season: Int
  stage: Int
  periods: GamePeriods!
  teams: GameTeams!
  scores: GameScores!
  officials: [String!]!
  timesTied: Int
  leadChanges: Int
  nugget: String
  createdAt: DateTime!
  updatedAt: DateTime!
  homeTeamId: String!
  awayTeamId: String!
  isCompleted: Boolean!
  awayTeamScore: Int
  homeTeamScore: Int
  gameType: String!
  nbaGameId: ID
}

type GameDate {
  start: DateTime!
  end: DateTime
  duration: Int
}

type GameStatus {
  clock: String
  halftime: Boolean!
  short: String!
  long: String!
}

type GamePeriods {
  current: Int!
  total: Int!
  endOfPeriod: Boolean!
}

type GameTeams {
  home: TeamSummary!
  visitors: TeamSummary!
}

type GameScores {
  home: TeamScore!
  visitors: TeamScore!
}

type TeamScore {
  win: Int!
  loss: Int!
  series: SeriesScore!
  linescore: [Int!]!
  points: Int!
}

type SeriesScore {
  win: Int!
  loss: Int!
}

type Arena {
  name: String!
  city: String
  state: String
  country: String
}

type GameLog {
  id: ID!
  game: Game!
  user: UserSummary!
  ratingForGame: Int!
  notes: String
  tags: [String!]
  watchedDate: DateTime
  watchedLocation: String
  watchedScope: String!
  watchedSetting: String!
  classification: Classification!
  comments(after: String, first: Int): CommentConnection!
  reactions: [Reaction!]!
  createdAt: DateTime!
  updatedAt: DateTime!
}

enum Classification {
  Private
  Protected
  Public
}

enum GameStatusEnum {
  SCHEDULED
  LIVE
  FINISHED
  CANCELLED
  POSTPONED
}

input CreateGameInput {
  awayTeamId: ID!
  awayTeamScore: Int
  date: DateTime!
  gameType: String!
  homeTeamId: ID!
  homeTeamScore: Int
  nbaGameId: ID
  status: GameStatusEnum!
}

input CreateGameLogInput {
  classification: Classification!
  gameId: ID!
  notes: String
  ratingForGame: Int!
  tags: [String!]
  watchedDate: DateTime
  watchedLocation: String
  watchedScope: String!
  watchedSetting: String!
}

type CreateGameResponse {
  errors: [ErrorResult!]
  game: Game
}

type CreateGameLogResponse {
  errors: [ErrorResult!]
  gameLog: GameLog
}
