import React from 'react';
import { type Metadata } from 'next';
import { ClerkProvider } from '@clerk/nextjs';
import Header from '../components/header';
import Footer from '../components/footer';
import { ThemeProvider } from '../components/theme-provider';
import { ApolloWrapper } from '../components/providers/apollo-provider';
import { Inter } from 'next/font/google';
import './styles/globals.css';
import { Toaster } from '@/components/ui/toaster';
import { AuthProvider } from '@/contexts/AuthContext';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart LOL',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth antialiased" suppressHydrationWarning>
      <body className={`flex min-h-screen flex-col ${inter.className}`}>
        <ClerkProvider>
          <AuthProvider>
            <ThemeProvider
              enableSystem
              attribute="class"
              defaultTheme="system"
              disableTransitionOnChange
            >
              <ApolloWrapper>
                <Header />
                <main className="grow">{children}</main>
                <Footer />
              </ApolloWrapper>
            </ThemeProvider>
            <Toaster />
          </AuthProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
