import { faker } from '@faker-js/faker';

export const possibleComments = [
  'Great game!',
  'What a finish!',
  "Can't believe that ending!",
  'The refs were terrible...',
  'MVP performance!',
  'Defense wins championships!',
  'Clutch play in the 4th!',
  'That was a nail-biter!',
  'Incredible comeback!',
  'The atmosphere was electric!',
  'Best game of the season!',
  'Those last few minutes were intense!',
  'The crowd was amazing!',
  'What a defensive masterclass!',
  'The offense was unstoppable!',
  'That play call was brilliant!',
  'The team chemistry is incredible!',
  'What a season this has been!',
  'The halftime adjustments worked perfectly!',
  'That player deserves all the praise!',
  'The coaching was spot on!',
  'What a way to end the game!',
  'The momentum shifts were crazy!',
  'That was a statement win!',
  'The energy in the stadium was unreal!',
  'The rookie stepped up big time!',
  'That trade deadline move paid off!',
  'The bench depth is incredible!',
  'What a defensive scheme!',
  'The fast break was unstoppable!',
  'That pick and roll was perfect!',
  'The three-point shooting was on fire!',
  'The post game was dominant!',
  'The transition defense needs work...',
  'The free throw shooting was clutch!',
  'The ball movement was beautiful!',
  'That timeout call was crucial!',
  'The rebounding battle was intense!',
  'The second unit really delivered!',
  'The home court advantage was real!',
  'The away crowd was silenced!',
  'The rivalry game lived up to the hype!',
  'The playoff atmosphere was intense!',
  'The championship DNA showed!',
  'The young core is promising!',
  'The veteran leadership was key!',
  'The injury comeback was inspiring!',
  'The record-breaking performance!',
  'The buzzer beater was insane!',
  'The overtime thriller!',
  'The defensive rotations were perfect!',
  'The offensive execution was flawless!',
  'The coaching chess match was fascinating!',
  'The player development is showing!',
  "The team's resilience was impressive!",
];

export const possibleReplies = [
  faker.lorem.sentence(),
  'I agree!',
  'Not sure about that...',
  'Great point!',
  "Couldn't have said it better!",
  faker.lorem.paragraph(1),
  'Absolutely right! The team really stepped up!',
  'I think we need to give credit to the coaching staff too!',
  "The stats don't lie, they dominated!",
  'What about that controversial call though?',
  'The bench players really contributed today!',
  'The home crowd advantage was huge!',
  'Their strategy was perfect for this matchup!',
  'I disagree, I think they got lucky!',
  'The preparation really showed!',
  'That player has been on fire lately!',
  'The team chemistry is at an all-time high!',
  'What do you think about the upcoming schedule?',
  'The momentum is definitely in their favor now!',
  'The adjustments at halftime were crucial!',
  'The defense really stepped up when it mattered!',
  'That was a game for the history books!',
  'The atmosphere was absolutely electric!',
  'They really showed their championship mentality!',
  'What a way to bounce back from last week!',
  'The analytics backed up their game plan perfectly!',
  'The player development program is really paying off!',
  'The scouting report was spot on!',
  'The conditioning made the difference in the 4th!',
  'The mental toughness was impressive!',
  "The team's depth is their biggest strength!",
  'The coaching adjustments won them this game!',
  'The veteran presence was crucial down the stretch!',
  'The young players are learning fast!',
  "The team's culture is really showing!",
  'The offseason moves are looking smart now!',
  "The player's work ethic is paying off!",
  "The team's identity is really clear!",
  'The defensive schemes were brilliant!',
  'The offensive sets were well executed!',
  "The team's resilience is remarkable!",
  "The player's versatility was key!",
  "The team's chemistry is at another level!",
  'The coaching staff deserves credit!',
  "The player's leadership was evident!",
  "The team's preparation was perfect!",
  "The player's improvement is noticeable!",
  "The team's execution was flawless!",
  "The player's confidence is growing!",
  "The team's potential is unlimited!",
  "The player's impact was huge!",
  "The team's future looks bright!",
  "The player's development is impressive!",
  "The team's consistency is remarkable!",
  "The player's growth is amazing!",
];
